### ISSUE TITLE
yarn, npm 모두 시도해봤는데 동일한 오류가 발생합니다.

### ISSUE THREAD

**Issue by javascriptbiggosoo** [performance-lecture/lecture-1#14]
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/tbs01215/IAD/lecture-1/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/tbs01215/IAD/lecture-1/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/tbs01215/IAD/lecture-1/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/tbs01215/IAD/lecture-1/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/tbs01215/IAD/lecture-1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/tbs01215/IAD/lecture-1/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

실행에서 막히는데 다른 분들은 어떤지 모르겠습니다.

**Comment by hackurity01** [comment]
안녕하세요,
node 문제로 아래 이슈와 동일한 문제 같습니다.
다음 이슈 확인해보시겠어요?
https://github.com/performance-lecture/lecture-1/issues/12

**Comment by javascriptbiggosoo** [comment]
> 안녕하세요, node 문제로 아래 이슈와 동일한 문제 같습니다. 다음 이슈 확인해보시겠어요? #12

버전 내리니 잘 됩니다. 감사합니다.
